web:
  build: ./setup/docker
  command: setup/docker/docker.start
  container_name: hoplajs
  ports: 
    - "8080:80"
    - "8443:443"
  volumes: 
    - ./:/var/www/docker

# Build:    `docker-compose build`
# Run:      `docker-compose up -d`
# Stop:     `docker-compose down`
# Shell:    `docker-compose exec web /bin/bash`
# dos2unix: `docker-compose run web bash -c 'dos2unix setup/docker/*'`